# Development Dockerfile

# Use a Node.js base image
FROM node:22-bullseye-slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the port your application runs on
EXPOSE 3000

# Command to start the application with hot reload
CMD ["npm", "run", "dev"]
