apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /storage/data
    type: DirectoryOrCreate
