apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: dev
type: Opaque
stringData:
  mongo-root-username: root
  mongo-root-password: example
  mongo-initdb-database: user_management_db
  MONGODB_URI: mongodb://root:example@mongo-0.mongo-headless.dev.svc.cluster.local:27017/user_management_db?authSource=admin
